################################################################################
# 02_sex_specific_lasso_protein_selection.R
#
# Sex-specific inflammatory and proteomic biomarkers associated with
# 10-year all-cause mortality risk
#
# Manuscript section:
#   Sex-specific inflammatory and proteomic biomarkers associated with
#   10-year all-cause mortality risk
#
# Purpose:
#   1. Read the organized UK Biobank derivation set generated by
#      01_data_extraction_baseline_characteristics.R.
#   2. Standardize Olink NPX protein values to z-scores using the UK Biobank
#      derivation set.
#   3. Perform sex-specific LASSO-regularized Cox regression in the UK Biobank
#      derivation set, with conventional mortality risk factors included as
#      unpenalized covariates.
#   4. Assess selection stability using 1,000 bootstrap resamples.
#   5. Retain proteins selected in at least 95% of bootstrap samples.
#
# Main outputs:
#   results/analysis_datasets/
#     ukb_derivation_standardized_target_inflammation.rds
#     ukb_derivation_standardized_explore.rds
#     protein_standardization_parameters_target_inflammation.csv
#     protein_standardization_parameters_explore.csv
#
#   results/selected_proteins/
#     selected_proteins_target_inflammation_men.csv
#     selected_proteins_target_inflammation_women.csv
#     selected_proteins_explore_men.csv
#     selected_proteins_explore_women.csv
#     selected_proteins_summary.csv
#
#   results/models/
#     lasso_cv_target_inflammation_men.rds
#     lasso_cv_target_inflammation_women.rds
#     lasso_cv_explore_men.rds
#     lasso_cv_explore_women.rds
#     bootstrap_selection_target_inflammation_men.rds
#     bootstrap_selection_target_inflammation_women.rds
#     bootstrap_selection_explore_men.rds
#     bootstrap_selection_explore_women.rds
#
# Notes:
#   - This script assumes that covariates and proteins have already been imputed,
#     consistent with the manuscript.
#   - Proteins are standardized to mean = 0 and SD = 1 in the UKB derivation set.
#   - In sex-stratified models, sex is not included as a covariate.
#   - Conventional risk factors are forced into the model by assigning
#     penalty.factor = 0 in glmnet.
################################################################################


# ==============================================================================
# 0. Packages
# ==============================================================================

required_packages <- c(
  "dplyr", "tidyr", "purrr", "stringr", "readr", "tibble",
  "survival", "glmnet", "Matrix", "doParallel", "foreach"
)

install_if_missing <- function(pkgs) {
  missing_pkgs <- pkgs[!pkgs %in% rownames(installed.packages())]
  if (length(missing_pkgs) > 0) install.packages(missing_pkgs)
  invisible(lapply(pkgs, library, character.only = TRUE))
}

install_if_missing(required_packages)


# ==============================================================================
# 1. User configuration
# ==============================================================================

set.seed(20240618)

# ---- Input from Part 1 ----
file_ukb_derivation <- "results/analysis_datasets/ukb_derivation.rds"

# ---- Protein list files ----
# One protein name per line. Names must match column names in ukb_derivation.rds.
file_target_inflammation_proteins <- "data/target_inflammation_proteins.txt"
file_explore_proteins             <- "data/explore_proteins.txt"

# ---- Output directories ----
dir_results  <- "results"
dir_dataout  <- file.path(dir_results, "analysis_datasets")
dir_selected <- file.path(dir_results, "selected_proteins")
dir_models   <- file.path(dir_results, "models")
dir_logs     <- file.path(dir_results, "logs")

dir.create(dir_dataout,  recursive = TRUE, showWarnings = FALSE)
dir.create(dir_selected, recursive = TRUE, showWarnings = FALSE)
dir.create(dir_models,   recursive = TRUE, showWarnings = FALSE)
dir.create(dir_logs,     recursive = TRUE, showWarnings = FALSE)

# ---- Core variables ----
sex_var   <- "sex_share"
time_var  <- "followup_time"
event_var <- "death_10y"

# Sex labels used in the dataset. Edit if your dataset uses different labels.
male_labels   <- c("Male", "Men", "M", "1", 1)
female_labels <- c("Female", "Women", "F", "0", 0, "2", 2)

# Conventional risk factors used in the LASSO-Cox models.
# Sex is removed automatically in sex-stratified analyses.
conventional_risk_factors <- c(
  "age_share",
  "sex_share",
  "education_share",
  "smoking_share",
  "activity_share",
  "alcohol_share",
  "BMI_share",
  "hypertension_share",
  "diabetes_share",
  "dyslipidemia_share",
  "CVD_share",
  "cancer_share"
)

# Continuous covariates. Age is modeled per 10-year increment.
continuous_covariates <- c("age_share")

# glmnet parameters
n_folds <- 10
lambda_choice <- "lambda.min"      # use "lambda.1se" for a more parsimonious model
n_bootstrap <- 1000
selection_frequency_threshold <- 0.95

# Parallel settings
use_parallel <- TRUE
n_cores <- max(1, parallel::detectCores() - 1)


# ==============================================================================
# 2. Helper functions
# ==============================================================================

read_protein_list <- function(path, panel_name) {
  if (!file.exists(path)) {
    stop("Protein list file not found for ", panel_name, ": ", path)
  }

  proteins <- readr::read_lines(path)
  proteins <- proteins[proteins != ""]
  proteins <- unique(trimws(proteins))

  if (length(proteins) == 0) {
    stop("No proteins found in: ", path)
  }

  proteins
}

standardize_proteins <- function(data, protein_vars, panel_name) {
  available_proteins <- intersect(protein_vars, names(data))
  missing_proteins <- setdiff(protein_vars, names(data))

  if (length(missing_proteins) > 0) {
    warning(
      panel_name, ": ", length(missing_proteins),
      " proteins were not found in the derivation dataset and will be ignored."
    )
    readr::write_lines(
      missing_proteins,
      file.path(dir_logs, paste0("missing_proteins_", panel_name, ".txt"))
    )
  }

  if (length(available_proteins) == 0) {
    stop("No available proteins for panel: ", panel_name)
  }

  center <- vapply(data[available_proteins], function(x) mean(as.numeric(x), na.rm = TRUE), numeric(1))
  scale  <- vapply(data[available_proteins], function(x) stats::sd(as.numeric(x), na.rm = TRUE), numeric(1))

  scale[is.na(scale) | scale == 0] <- 1

  standardized <- data
  standardized[available_proteins] <- purrr::map2(
    standardized[available_proteins],
    available_proteins,
    ~ (as.numeric(.x) - center[.y]) / scale[.y]
  )

  scaling_parameters <- tibble::tibble(
    panel = panel_name,
    protein = available_proteins,
    center = as.numeric(center[available_proteins]),
    scale = as.numeric(scale[available_proteins])
  )

  readr::write_csv(
    scaling_parameters,
    file.path(dir_dataout, paste0("protein_standardization_parameters_", panel_name, ".csv"))
  )

  list(
    data = standardized,
    proteins = available_proteins,
    scaling_parameters = scaling_parameters
  )
}

standardize_sex <- function(x) {
  x_chr <- as.character(x)
  dplyr::case_when(
    x_chr %in% as.character(male_labels) ~ "Men",
    x_chr %in% as.character(female_labels) ~ "Women",
    TRUE ~ x_chr
  )
}

prepare_model_data <- function(data, protein_vars, sex_level) {
  dat <- data %>%
    dplyr::mutate(sex_standardized = standardize_sex(.data[[sex_var]])) %>%
    dplyr::filter(sex_standardized == sex_level)

  covariates <- setdiff(conventional_risk_factors, sex_var)
  covariates <- intersect(covariates, names(dat))

  required_vars <- c(time_var, event_var, covariates, protein_vars)
  missing_vars <- setdiff(required_vars, names(dat))
  if (length(missing_vars) > 0) {
    stop("Missing variables for ", sex_level, ": ", paste(missing_vars, collapse = ", "))
  }

  analysis_dat <- dat[, required_vars, drop = FALSE]

  analysis_dat[[time_var]] <- as.numeric(analysis_dat[[time_var]])
  analysis_dat[[event_var]] <- as.integer(as.numeric(as.character(analysis_dat[[event_var]])) == 1)

  for (v in covariates) {
    if (v %in% continuous_covariates) {
      analysis_dat[[v]] <- as.numeric(analysis_dat[[v]])
      if (v == "age_share") {
        analysis_dat[[v]] <- analysis_dat[[v]] / 10
      }
    } else {
      analysis_dat[[v]] <- as.factor(analysis_dat[[v]])
    }
  }

  # Reference levels used in the original analysis scripts.
  if ("BMI_share" %in% names(analysis_dat)) {
    analysis_dat$BMI_share <- as.factor(analysis_dat$BMI_share)
    if (nlevels(analysis_dat$BMI_share) >= 2) {
      analysis_dat$BMI_share <- stats::relevel(
        analysis_dat$BMI_share,
        ref = levels(analysis_dat$BMI_share)[2]
      )
    }
  }

  if ("alcohol_share" %in% names(analysis_dat)) {
    analysis_dat$alcohol_share <- as.factor(analysis_dat$alcohol_share)
    if (nlevels(analysis_dat$alcohol_share) >= 2) {
      analysis_dat$alcohol_share <- stats::relevel(
        analysis_dat$alcohol_share,
        ref = tail(levels(analysis_dat$alcohol_share), 1)
      )
    }
  }

  for (p in protein_vars) {
    analysis_dat[[p]] <- as.numeric(analysis_dat[[p]])
  }

  analysis_dat <- analysis_dat %>%
    dplyr::filter(!is.na(.data[[time_var]]), .data[[time_var]] > 0) %>%
    tidyr::drop_na() %>%
    droplevels()

  if (nrow(analysis_dat) == 0) stop("No complete observations for ", sex_level)
  if (sum(analysis_dat[[event_var]] == 1) == 0) stop("No events for ", sex_level)

  # Remove covariates with no variation after sex stratification and complete-case filtering.
  covariates_final <- covariates[purrr::map_lgl(covariates, function(v) {
    if (is.factor(analysis_dat[[v]])) {
      nlevels(analysis_dat[[v]]) >= 2
    } else {
      stats::sd(analysis_dat[[v]], na.rm = TRUE) > 0
    }
  })]

  list(
    data = analysis_dat,
    covariates = covariates_final,
    proteins = protein_vars
  )
}

make_glmnet_matrix <- function(data, covariates, proteins) {
  predictors <- c(covariates, proteins)

  mm <- stats::model.matrix(
    stats::as.formula(paste("~", paste(predictors, collapse = " + "))),
    data = data
  )

  x <- mm[, colnames(mm) != "(Intercept)", drop = FALSE]
  y <- survival::Surv(data[[time_var]], data[[event_var]])

  # glmnet expands categorical covariates into multiple dummy variables.
  # Protein columns keep their original names because they are numeric.
  protein_columns <- colnames(x) %in% proteins

  penalty_factor <- ifelse(protein_columns, 1, 0)

  list(
    x = x,
    y = y,
    penalty_factor = penalty_factor,
    protein_columns = protein_columns,
    predictors = predictors
  )
}

extract_selected_proteins <- function(cvfit, protein_vars, lambda = lambda_choice) {
  beta <- as.matrix(stats::coef(cvfit, s = lambda))
  selected_terms <- rownames(beta)[as.numeric(beta[, 1]) != 0]
  intersect(selected_terms, protein_vars)
}

fit_lasso_cox <- function(model_data, alpha = 1) {
  mm <- make_glmnet_matrix(
    data = model_data$data,
    covariates = model_data$covariates,
    proteins = model_data$proteins
  )

  cvfit <- glmnet::cv.glmnet(
    x = mm$x,
    y = mm$y,
    family = "cox",
    alpha = alpha,
    nfolds = n_folds,
    penalty.factor = mm$penalty_factor,
    standardize = FALSE,
    type.measure = "deviance",
    parallel = use_parallel
  )

  selected <- extract_selected_proteins(cvfit, model_data$proteins, lambda = lambda_choice)

  list(
    cvfit = cvfit,
    selected = selected,
    model_matrix_columns = colnames(mm$x),
    penalty_factor = mm$penalty_factor
  )
}

bootstrap_lasso_selection <- function(model_data, panel_name, sex_level) {
  dat <- model_data$data
  proteins <- model_data$proteins

  protein_selection_counts <- setNames(rep(0L, length(proteins)), proteins)

  for (b in seq_len(n_bootstrap)) {
    boot_index <- sample(seq_len(nrow(dat)), size = nrow(dat), replace = TRUE)
    boot_data <- dat[boot_index, , drop = FALSE] %>% droplevels()

    boot_model_data <- list(
      data = boot_data,
      covariates = model_data$covariates,
      proteins = model_data$proteins
    )

    fit_b <- tryCatch(
      fit_lasso_cox(boot_model_data),
      error = function(e) {
        message("Bootstrap error in ", panel_name, " / ", sex_level, " / iteration ", b, ": ", e$message)
        NULL
      }
    )

    if (!is.null(fit_b)) {
      protein_selection_counts[fit_b$selected] <- protein_selection_counts[fit_b$selected] + 1L
    }

    if (b %% 50 == 0) {
      message(panel_name, " / ", sex_level, ": bootstrap ", b, " of ", n_bootstrap)
    }
  }

  stability_table <- tibble::tibble(
    panel = panel_name,
    sex = sex_level,
    protein = names(protein_selection_counts),
    selection_count = as.integer(protein_selection_counts),
    selection_frequency = as.numeric(protein_selection_counts) / n_bootstrap,
    selected_stable = selection_frequency >= selection_frequency_threshold
  ) %>%
    dplyr::arrange(dplyr::desc(selection_frequency), protein)

  selected_stable <- stability_table %>%
    dplyr::filter(selected_stable) %>%
    dplyr::pull(protein)

  list(
    stability_table = stability_table,
    selected_stable = selected_stable
  )
}

run_panel_selection <- function(data, protein_vars, panel_name) {
  message("\n==============================")
  message("Panel: ", panel_name)
  message("==============================")

  standardized <- standardize_proteins(data, protein_vars, panel_name)

  readr::write_rds(
    standardized$data,
    file.path(dir_dataout, paste0("ukb_derivation_standardized_", panel_name, ".rds"))
  )

  panel_results <- list()

  for (sex_level in c("Men", "Women")) {
    message("\nRunning sex-specific LASSO-Cox selection: ", panel_name, " / ", sex_level)

    model_data <- prepare_model_data(
      data = standardized$data,
      protein_vars = standardized$proteins,
      sex_level = sex_level
    )

    cv_result <- fit_lasso_cox(model_data)

    cv_output_file <- file.path(dir_models, paste0("lasso_cv_", panel_name, "_", tolower(sex_level), ".rds"))
    readr::write_rds(cv_result, cv_output_file)

    initial_selection <- tibble::tibble(
      panel = panel_name,
      sex = sex_level,
      selection_stage = "cv_lasso",
      protein = cv_result$selected
    )

    bootstrap_result <- bootstrap_lasso_selection(model_data, panel_name, sex_level)

    bootstrap_output_file <- file.path(
      dir_models,
      paste0("bootstrap_selection_", panel_name, "_", tolower(sex_level), ".rds")
    )
    readr::write_rds(bootstrap_result, bootstrap_output_file)

    stable_selection <- bootstrap_result$stability_table %>%
      dplyr::filter(selected_stable) %>%
      dplyr::mutate(selection_stage = "bootstrap_stable") %>%
      dplyr::select(panel, sex, selection_stage, protein, selection_count, selection_frequency)

    output_csv <- file.path(
      dir_selected,
      paste0("selected_proteins_", panel_name, "_", tolower(sex_level), ".csv")
    )

    readr::write_csv(stable_selection, output_csv)

    readr::write_csv(
      bootstrap_result$stability_table,
      file.path(dir_selected, paste0("selection_stability_", panel_name, "_", tolower(sex_level), ".csv"))
    )

    panel_results[[sex_level]] <- list(
      model_data_summary = tibble::tibble(
        panel = panel_name,
        sex = sex_level,
        n = nrow(model_data$data),
        events = sum(model_data$data[[event_var]] == 1),
        n_proteins_available = length(model_data$proteins),
        n_cv_selected = length(cv_result$selected),
        n_bootstrap_stable_selected = length(bootstrap_result$selected_stable)
      ),
      cv_selected = initial_selection,
      stable_selected = stable_selection,
      stability_table = bootstrap_result$stability_table,
      cv_model_file = cv_output_file,
      bootstrap_file = bootstrap_output_file
    )
  }

  panel_results
}


# ==============================================================================
# 3. Load UKB derivation set and protein lists
# ==============================================================================

if (!file.exists(file_ukb_derivation)) {
  stop(
    "UKB derivation RDS not found: ", file_ukb_derivation,
    "\nRun 01_data_extraction_baseline_characteristics.R first."
  )
}

ukb_derivation <- readr::read_rds(file_ukb_derivation)

target_inflammation_proteins <- read_protein_list(
  file_target_inflammation_proteins,
  panel_name = "target_inflammation"
)

explore_proteins <- read_protein_list(
  file_explore_proteins,
  panel_name = "explore"
)


# ==============================================================================
# 4. Register parallel backend
# ==============================================================================

if (use_parallel) {
  cl <- parallel::makeCluster(n_cores)
  doParallel::registerDoParallel(cl)
  on.exit({
    try(parallel::stopCluster(cl), silent = TRUE)
    foreach::registerDoSEQ()
  }, add = TRUE)
}


# ==============================================================================
# 5. Run sex-specific LASSO-Cox selection in UKB derivation set
# ==============================================================================

selection_target_inflammation <- run_panel_selection(
  data = ukb_derivation,
  protein_vars = target_inflammation_proteins,
  panel_name = "target_inflammation"
)

selection_explore <- run_panel_selection(
  data = ukb_derivation,
  protein_vars = explore_proteins,
  panel_name = "explore"
)


# ==============================================================================
# 6. Export summary tables for manuscript reporting
# ==============================================================================

selection_summary <- dplyr::bind_rows(
  selection_target_inflammation$Men$model_data_summary,
  selection_target_inflammation$Women$model_data_summary,
  selection_explore$Men$model_data_summary,
  selection_explore$Women$model_data_summary
)

readr::write_csv(
  selection_summary,
  file.path(dir_selected, "selected_proteins_summary.csv")
)

selected_proteins_all <- dplyr::bind_rows(
  selection_target_inflammation$Men$stable_selected,
  selection_target_inflammation$Women$stable_selected,
  selection_explore$Men$stable_selected,
  selection_explore$Women$stable_selected
)

readr::write_csv(
  selected_proteins_all,
  file.path(dir_selected, "selected_proteins_all_panels.csv")
)

selection_stability_all <- dplyr::bind_rows(
  selection_target_inflammation$Men$stability_table,
  selection_target_inflammation$Women$stability_table,
  selection_explore$Men$stability_table,
  selection_explore$Women$stability_table
)

readr::write_csv(
  selection_stability_all,
  file.path(dir_selected, "selection_stability_all_panels.csv")
)

# Save an RDS object that can be loaded directly by Part 3.
readr::write_rds(
  list(
    target_inflammation = selection_target_inflammation,
    explore = selection_explore
  ),
  file.path(dir_models, "sex_specific_lasso_selection_all_panels.rds")
)


# ==============================================================================
# 7. Console summary
# ==============================================================================

cat("\nSex-specific LASSO-Cox protein selection completed successfully.\n")
cat("\nStable selected proteins:\n")
print(selection_summary)

cat("\nGenerated outputs:\n")
cat("  - Standardized UKB derivation datasets: ", dir_dataout, "\n", sep = "")
cat("  - Selected protein tables: ", dir_selected, "\n", sep = "")
cat("  - LASSO-Cox and bootstrap model objects: ", dir_models, "\n", sep = "")


# ==============================================================================
# 8. Forest plots for LASSO-selected proteins: adjusted HRs
# ==============================================================================

required_packages_forest <- c("ggplot2", "ggthemes", "officer", "rvg", "svglite")
install_if_missing(required_packages_forest)

dir_figures <- file.path(dir_results, "figures")
dir.create(dir_figures, recursive = TRUE, showWarnings = FALSE)

file_ukb_internal <- "results/analysis_datasets/ukb_internal_validation.rds"
file_esther_ti <- "results/analysis_datasets/esther_target_inflammation.rds"
file_esther_ht <- "results/analysis_datasets/esther_explore_ht.rds"

apply_protein_standardization <- function(data, scaling_file){
  scaling <- readr::read_csv(scaling_file, show_col_types = FALSE)
  proteins <- intersect(scaling$protein, names(data))
  out <- data
  for(p in proteins){
    center_p <- scaling$center[match(p, scaling$protein)]
    scale_p <- scaling$scale[match(p, scaling$protein)]
    if(is.na(scale_p) || scale_p == 0) scale_p <- 1
    out[[p]] <- (as.numeric(out[[p]]) - center_p) / scale_p
  }
  out
}

prepare_forest_data <- function(data, protein, sex_level){
  dat <- data %>%
    mutate(sex_standardized = standardize_sex(.data[[sex_var]])) %>%
    filter(sex_standardized == sex_level)
  
  covariates <- setdiff(conventional_risk_factors, sex_var)
  covariates <- intersect(covariates, names(dat))
  required_vars <- c(time_var, event_var, protein, covariates)
  
  dat <- dat[, required_vars, drop = FALSE]
  dat[[time_var]] <- as.numeric(dat[[time_var]])
  dat[[event_var]] <- as.integer(as.numeric(as.character(dat[[event_var]])) == 1)
  dat[[protein]] <- as.numeric(dat[[protein]])
  
  for(v in covariates){
    if(v %in% continuous_covariates){
      dat[[v]] <- as.numeric(dat[[v]])
      if(v == "age_share") dat[[v]] <- dat[[v]] / 10
    } else {
      dat[[v]] <- as.factor(dat[[v]])
    }
  }
  
  dat <- dat %>%
    filter(!is.na(.data[[time_var]]), .data[[time_var]] > 0) %>%
    tidyr::drop_na() %>%
    droplevels()
  
  covariates_final <- covariates[purrr::map_lgl(covariates, function(v){
    if(is.factor(dat[[v]])) nlevels(dat[[v]]) >= 2 else stats::sd(dat[[v]], na.rm = TRUE) > 0
  })]
  
  list(data = dat, covariates = covariates_final)
}

run_protein_cox <- function(data, protein, sex_level, dataset_name, panel_name){
  obj <- prepare_forest_data(data, protein, sex_level)
  dat <- obj$data
  covariates <- obj$covariates
  
  if(nrow(dat) == 0 || sum(dat[[event_var]] == 1, na.rm = TRUE) == 0){
    return(tibble(
      panel = panel_name,
      sex = sex_level,
      dataset = dataset_name,
      protein = protein,
      HR = NA_real_,
      CI_lower = NA_real_,
      CI_upper = NA_real_,
      P_value = NA_real_
    ))
  }
  
  fml <- as.formula(
    paste0(
      "survival::Surv(", time_var, ",", event_var, ") ~ ",
      paste(c(protein, covariates), collapse = " + ")
    )
  )
  
  fit <- survival::coxph(fml, data = dat)
  broom::tidy(fit, exponentiate = TRUE, conf.int = TRUE) %>%
    filter(term == protein) %>%
    transmute(
      panel = panel_name,
      sex = sex_level,
      dataset = dataset_name,
      protein = protein,
      HR = estimate,
      CI_lower = conf.low,
      CI_upper = conf.high,
      P_value = p.value
    )
}

make_forest_input <- function(panel_name, derivation_data, internal_data, external_data){
  selected_panel <- selected_proteins_all %>%
    filter(panel == panel_name) %>%
    select(panel, sex, protein) %>%
    distinct()
  
  purrr::pmap_dfr(selected_panel, function(panel, sex, selection_stage = NULL, protein, ...){
    bind_rows(
      run_protein_cox(derivation_data, protein, sex, "70% UKB", panel_name),
      run_protein_cox(internal_data, protein, sex, "30% UKB", panel_name),
      run_protein_cox(external_data, protein, sex, "ESTHER", panel_name)
    )
  }) %>%
    group_by(panel, sex, dataset) %>%
    mutate(FDR = p.adjust(P_value, method = "BH")) %>%
    ungroup()
}

plot_forest_by_sex <- function(dat, sex_label, xlab_text){
  df_sex <- dat %>%
    filter(sex == sex_label) %>%
    mutate(
      dataset = factor(dataset, levels = c("70% UKB", "30% UKB", "ESTHER")),
      dataset_label = dataset
    )
  
  protein_order <- df_sex %>%
    filter(dataset == "70% UKB") %>%
    arrange(desc(HR)) %>%
    pull(protein) %>%
    unique()
  
  df_sex <- df_sex %>%
    mutate(
      protein_f = factor(protein, levels = rev(protein_order)),
      base_y = as.numeric(protein_f) * 1.4,
      offset = case_when(
        dataset == "70% UKB" ~ 0.22,
        dataset == "30% UKB" ~ 0,
        dataset == "ESTHER" ~ -0.22
      ),
      y = base_y + offset
    )
  
  validated <- df_sex %>%
    filter(dataset %in% c("30% UKB", "ESTHER")) %>%
    group_by(protein) %>%
    summarise(validated = all(FDR < 0.05, na.rm = TRUE), .groups = "drop")
  
  tick_df <- df_sex %>%
    distinct(protein, protein_f) %>%
    left_join(validated, by = "protein") %>%
    mutate(
      y_tick = as.numeric(protein_f) * 1.4,
      protein_label = ifelse(validated, paste0(protein, "*"), protein)
    )
  
  ggplot(df_sex, aes(x = HR, y = y, color = dataset_label)) +
    geom_errorbarh(aes(xmin = CI_lower, xmax = CI_upper), height = 0, linewidth = 0.7) +
    geom_point(size = 2.2) +
    geom_vline(xintercept = 1, linetype = "dashed", color = "grey40") +
    scale_y_continuous(breaks = tick_df$y_tick, labels = tick_df$protein_label) +
    scale_x_log10(name = xlab_text) +
    scale_color_manual(values = c("70% UKB" = "#1A2930", "30% UKB" = "#A51C30", "ESTHER" = "#6A51A3")) +
    ggthemes::theme_few() +
    theme(
      legend.title = element_blank(),
      legend.position = "top",
      axis.title.y = element_blank(),
      axis.text.y = element_text(size = 11, color = "black", face = "italic"),
      axis.text.x = element_text(size = 11, color = "black"),
      panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
      plot.title = element_text(hjust = 0, size = 12, face = "bold")
    ) +
    ggtitle(sex_label)
}

export_forest_plots <- function(dat, panel_name, file_prefix){
  p_men <- plot_forest_by_sex(dat, "Men", "Adjusted HR per 1-SD increment")
  p_women <- plot_forest_by_sex(dat, "Women", "Adjusted HR per 1-SD increment")
  
  ggsave(file.path(dir_figures, paste0(file_prefix, "_men.pdf")), p_men, width = 4.5, height = 8)
  ggsave(file.path(dir_figures, paste0(file_prefix, "_women.pdf")), p_women, width = 4.5, height = 8)
  ggsave(file.path(dir_figures, paste0(file_prefix, "_men.png")), p_men, width = 4.5, height = 8, dpi = 600)
  ggsave(file.path(dir_figures, paste0(file_prefix, "_women.png")), p_women, width = 4.5, height = 8, dpi = 600)
  
  svglite::svglite(file.path(dir_figures, paste0(file_prefix, "_men.svg")), width = 4.5, height = 8)
  print(p_men)
  dev.off()
  
  svglite::svglite(file.path(dir_figures, paste0(file_prefix, "_women.svg")), width = 4.5, height = 8)
  print(p_women)
  dev.off()
  
  pptx_file <- file.path(dir_figures, paste0(file_prefix, "_editable.pptx"))
  doc <- officer::read_pptx()
  doc <- officer::add_slide(doc, layout = "Blank", master = "Office Theme")
  doc <- officer::ph_with(doc, rvg::dml(code = print(p_men)), location = officer::ph_location(width = 4.5, height = 8))
  doc <- officer::add_slide(doc, layout = "Blank", master = "Office Theme")
  doc <- officer::ph_with(doc, rvg::dml(code = print(p_women)), location = officer::ph_location(width = 4.5, height = 8))
  print(doc, target = pptx_file)
}

ukb_internal_raw <- readr::read_rds(file_ukb_internal)
esther_ti_raw <- readr::read_rds(file_esther_ti)
esther_ht_raw <- readr::read_rds(file_esther_ht)

ukb_internal_ti <- apply_protein_standardization(
  ukb_internal_raw,
  file.path(dir_dataout, "protein_standardization_parameters_target_inflammation.csv")
)

ukb_internal_explore <- apply_protein_standardization(
  ukb_internal_raw,
  file.path(dir_dataout, "protein_standardization_parameters_explore.csv")
)

esther_ti <- apply_protein_standardization(
  esther_ti_raw,
  file.path(dir_dataout, "protein_standardization_parameters_target_inflammation.csv")
)

esther_ht <- apply_protein_standardization(
  esther_ht_raw,
  file.path(dir_dataout, "protein_standardization_parameters_explore.csv")
)

forest_target_inflammation <- make_forest_input(
  panel_name = "target_inflammation",
  derivation_data = selection_target_inflammation$Men$model_data_summary %>% {readr::read_rds(file.path(dir_dataout, "ukb_derivation_standardized_target_inflammation.rds"))},
  internal_data = ukb_internal_ti,
  external_data = esther_ti
)

forest_explore <- make_forest_input(
  panel_name = "explore",
  derivation_data = selection_explore$Men$model_data_summary %>% {readr::read_rds(file.path(dir_dataout, "ukb_derivation_standardized_explore.rds"))},
  internal_data = ukb_internal_explore,
  external_data = esther_ht
)

readr::write_csv(forest_target_inflammation, file.path(dir_selected, "Figure_1A_forest_target_inflammation_HR.csv"))
readr::write_csv(forest_explore, file.path(dir_selected, "Figure_1B_forest_explore_HR.csv"))

export_forest_plots(
  forest_target_inflammation,
  panel_name = "target_inflammation",
  file_prefix = "Figure_1A_forest_target_inflammation"
)

export_forest_plots(
  forest_explore,
  panel_name = "explore",
  file_prefix = "Figure_1B_forest_explore"
)

cat("\nForest plots for Figure 1A-B completed.\n")
